Routes for reward and task
UTBootCampGroup2Project2/reward-bank pull request #17
Opened 2021-03-20 15:05 UTC by cerafinn

Completed routes for reward and task routes

2021-03-20 15:41 UTC, BrianCKWang requested changes
Made some comments to change for the PUT that fixes the server error

2021-03-20 15:41 UTC, BrianCKWang commented on controllers/api/reward-routes.js
> +  Reward.update({ where: { id: req.params.id } },
`Reward.update(`

2021-03-20 15:41 UTC, BrianCKWang commented on controllers/api/reward-routes.js
> +  })
`}, { where: { id: req.params.id } } )`

2021-03-20 15:41 UTC, BrianCKWang commented on controllers/api/task-routes.js
> +  Task.update({ where: { id: req.params.id } },
`Task.update(`

2021-03-20 15:41 UTC, BrianCKWang commented on controllers/api/task-routes.js
> +  })
`}, { where: { id: req.params.id } })`

2021-03-21 00:01 UTC, cerafinn commented
Reworked the routes and will resubmit new pull request

2021-03-21 00:01 UTC, closed without merging